List stateAgency = [
  'Agency for Non-conventional Energy and Rural Technology',
  'Ammathottil',
  'Excise Academy and Research Centre',
  'Gender Park',
  'Goshree Islands Development Authority',
  'Greater Cochin Development Authority',
  'Kerala State Human Rights Commission',
  'Information and Communication Technology Academy of Kerala',
  'Jawaharlal Nehru Tropical Botanic Garden and Research Institute',
  'Kerala Excise',
  'Kerala Financial Corporation',
  'Kerala Fire And Rescue Services',
  'Kerala Forest Research Institute',
  'Kerala Industrial Infrastructure Development Corporation',
  'Kerala Infrastructure Investment Fund Board',
  'Kerala Institute of Local Administration',
  'Kerala Public Service Commission',
  'Kerala Shipping and Inland Navigation Corporation',
  'The Kerala State Biodiversity Board',
  'Kerala State Civil Supplies Corporation',
  'Kerala State Council for Science, Technology and Environment',
  'Kerala State Development Corporation for Christian Converts from Scheduled Castes and the Recommended Communities',
  'Kerala State Drugs and Pharmaceuticals Limited',
  'Kerala State Film Development Corporation',
  'Kerala State Financial Enterprises',
  'Kerala State Horticulture Mission',
  'Kerala State Industrial Development Corporation',
  'Kerala State Institute of Design',
  'Kerala State Land Bank',
  'Kerala State Legal Services Authority',
  'Kerala State Lotteries',
  'Kerala State Pollution Control Board',
  'Kerala State Road Transport Corporation',
  'Kerala Tourism Development Corporation',
  'Kerala Tulu Academy',
  'Kerala Urban Road Transport Corporation',
  'Kerala Water Authority',
  'Kollam Development Authority',
  'Kerala State IT Mission',
  'Roads and Bridges Development Corporation',
  'State Council of Educational Research and Training, Kerala',
  'State Finance Commission (Kerala)',
  'State Institute of Encyclopaedic Publications',
  'Steel and Industrial Forgings Ltd',
  'Steel Industries Kerala Limited',
  'Thiruvananthapuram Development Authority',
  'Thrissur Development Authority',
  'Thrissur-Ponnani Kole Land Development Council',
  'Tourist Resorts (Kerala)',
  'Trivandrum Rubber Works',
];
